dist: trusty

language: c

sudo: true

env:
  global:
    - LUAVER=5.3.5
    - LUAROCKSVER=3.0.4
    - PATH=$PATH:$HOME/.luarocks/bin

branches:
  only:
    - master

before_install:
  - pushd $(pwd)
  - wget -O - https://www.lua.org/ftp/lua-$LUAVER.tar.gz | tar -xz
  - cd lua-$LUAVER && make linux
  - sudo make install
  - wget -O - http://luarocks.github.io/luarocks/releases/luarocks-$LUAROCKSVER.tar.gz | tar -xz
  - cd luarocks-$LUAROCKSVER && ./configure && make
  - sudo make install
  - luarocks install busted --local
  - luarocks install luacov --local
  - luarocks install luacov-coveralls --local --server=https://luarocks.org/dev
  - popd

install:
  - luarocks make --local

script:
  - busted -c

after_success:
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
