language: c

sudo: false

env:
  global:
    - LUAVER=5.3.5
    - LUAROCKSVER=3.0.4
    - PATH=$PATH:$TRAVIS_BUILD_DIR/bin

branches:
  only:
    - master

before_install:
  - wget -O - https://www.lua.org/ftp/lua-$LUAVER.tar.gz | tar -xz
  - cd lua-$LUAVER && make linux && make install INSTALL_TOP=$TRAVIS_BUILD_DIR
  - wget -O - http://luarocks.github.io/luarocks/releases/luarocks-$LUAROCKSVER.tar.gz | tar -xz
  - cd luarocks-$LUAROCKSVER && ./configure --prefix=$TRAVIS_BUILD_DIR && make && make install
  - luarocks install busted

install:
  - luarocks make

script:
  - busted

after_success:

notifications:
  email:
    on_success: change
    on_failure: always
